#!/bin/bash
#
# Update script for SaberMod gcc server
git checkout 4.8.5 && git fetch smhub 4.8.5 && git merge smhub/4.8.5 && git fetch gnu gcc-4_8-branch && git merge FETCH_HEAD;
git checkout 4.9.4 && git fetch smhub 4.9.4 && git merge smhub/4.9.4 && git fetch gnu gcc-4_9-branch && git merge FETCH_HEAD;
git checkout 5.2.0 && git fetch smhub 5.2.0 git merge smhub/5.2.0 && git fetch gnu gcc-5-branch && git merge FETCH_HEAD;
git checkout 6.0.0 && git fetch smhub 6.0.0 && git merge smhub/6.0.0 && git fetch gnu trunk && git merge FETCH_HEAD;
git push smhub --all;
